### PR TITLE
Fix issue #15 - tab character support

### PR DESCRIPTION
**Pull request by clach04**
Do not print out black boxes if tabs are in file when new parameter
`--tab-size` is specified.

Some of the code is based on code from smart_code_copier.py by
https://github.com/zchrissirhcz (no known code repo by this owner)
See https://github.com/ariacheng/smart_code_copier (also MIT license)

### CODE REVIEW

**Comment by clach04** [comment]
@baruchel thanks so much for making this tool available!

**Comment by baruchel** [comment]
@clach04 Hi, thank you for your contributions; to be frank, I have used my own software for years until switching to another markdown-based workflow. I am not sure I could still understand the code now without taking some time. Would you agree getting editor rights on this project? Regards.

**Comment by clach04** [comment]
@baruchel yes I can do that. The code is pretty complete and stable so I'm not expecting many changes.

Out of curiosity what software are you using these days? Personally I'm using Pandoc and also https://github.com/trentm/python-markdown2 - but for the use case I had, for generating PDFs, your tool was the easiest and gave the best+consistent results (better than Pandoc!)

**Comment by baruchel** [comment]
@clach04 I initially wrote this script because I wanted to print my lectures for my students (I don't mind the monospace typesetting and students learnt to recognize my own way of formatting documents - some actually remembered specifically that point years later), but now I use a git-based workflow (having my markdown documents directly rendered on the browser, and I don't print documents on paper any longer for ecological reasons).

**Pull request merged**
